### ISSUE TITLE
Infinite runtime for in-the-money options

### ISSUE THREAD

**Issue by lacksfish** [gurhanc/Black-Scholes-Calculator#1]
Given the following parameters, the approximation does not finish.

`newton_vol_vanilla_option(170.1, 150, 0.010, 20, 0, sigma=0.66, type='call')`

This option, with a cost of $20, is in the money by $0.1 and the function is not working for this case.

It works up until $170, which is exactly the strike price of $150 plus the option premium of $20.
`newton_vol_vanilla_option(170, 150, 0.010, 20, 0, sigma=0.66, type='call')`

**Comment by lacksfish** [comment]
I'm assuming the function was borrowed from https://aaronschlegel.me/implied-volatility-functions-python.html#Non-dividend-paying-asset ?

**Comment by gurhanc** [comment]
First, thanks for your comment. 
The model is dependent on valid input. From your example, if the spot price is 170.1 and strike is 150, option premium shouldn't be lower than 20.1 since current price is 20.1 (170.1-150) assuming even zero interest. You shouldn't be willing to get less money than that cause other side will reverse the order and obtain an immediate profit from that:)
But, anyway, your comment should make me to put a counter for maximum number of iterations, such as ie 20, so that if the iteration don't give any solution, we can print no solution due to invalid input etc.
Thanks again.

**Comment by gurhanc** [comment]
I'm closing this if you don't have any other question. Thanks.
